---
  
- name: install postgresql
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - postgresql

- name: configure postgresql.conf
  template:
    src: postgresql.conf
    dest: /etc/postgresql/9.5/main/
    mode: 0644

- name: start postgresql service
  service:
    name: postgresql
    state: started
    enabled: yes

