- name: install keepalived 
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - keepalived

- name: install floating ip assigner
  template:
    src: assign-ip
    dest: /usr/local/bin/assign-ip
    mode: 0755

- name: install keepalived script
  template:
    src: master.sh
    dest: /etc/keepalived/master.sh
    mode: 0755

- name: restart keepalived
  service: 
    name: keepalived
    state: restarted
    enabled: yes
