- name: install keepalived and heartbeat
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - keepalived
    - heartbeat

  #- name: configure keepalived
  #  template:
  #  src: keepalived.conf
  #  dest: /etc/keepalived/keepalived.conf
  #  mode: 0644

#- name: configure heartbeat
#  template:
#    src: ha.cf
#    dest: /etc/ha.d/ha.cf
#    mode: 0644

#- name: configura haresources
#  template:
#    src: haresources
#    dest: /etc/ha.d/haresources

#- name: configure authkey
#  template:
#    src: authkeys
#    dest: /etc/ha.d/authkeys
#    mode: 0600

- name: install floating ip assigner
  template:
    src: assign-ip
    dest: /usr/local/bin/assign-ip
    mode: 0755

#- name: install floating ip manager
#  template:
#    src: floatip
#    dest: /etc/init.d/floatip
#    mode: 0755

- name: install keepalived script
  template:
    src: master.sh
    dest: /etc/keepalived/master.sh
    mode: 0755

- name: start keepalived
  service: 
    name: keepalived
    state: started
    enabled: yes

#- name: start heartbeat service
#  service:
#    name: heartbeat
#    state: started
#    enabled: yes
